name: CI
on: [push, pull_request]

jobs:
  test-example:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Checkout extism/cli
        uses: actions/checkout@v3
        with:
          repository: extism/cli
          path: cli

      - name: Install Extism & CLI
        run: |
          pushd cli
          pip3 install cffi
          pip3 install .
          popd

          extism install git

      - uses: workflow/nix-shell-action@v3
        with:
        packages: https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/archive/master/ghc-wasm-meta-master.tar.gz
        script: |
          make

      - name: Test call command
        run: |
          TEST=$(extism call ./count_vowels.wasm _start --wasi --input "this is a test")
          echo $TEST | grep '"count": 4'

          TEST=$(extism call ./hello.wasm _start --wasi --input "Name" --config greeting="Hi there")
          echo $TEST | grep 'Hi there, Name"

          TEST=$(extism call ./http_get.wasm _start --wasi --input "https://jsonplaceholder.typicode.com/todos/1")
          echo $TEST | grep '"userId": 1'
